#!/bin/sh

INSTALL_DIR=~/.dotfiles

if [ ! -d ${INSTALL_DIR} ]; then
	echo "Ops! dotfies must be installed on ${INSTALL_DIR}"
	exit 1
fi

deploy() {
	[ -f ${2} ] && rm -f ${2}
	ln -s ${1} ${2}
}

clone() {
	if [ -d ${2} ]; then
		cd ${2} && git pull --rebase
	else
		git clone --recursive ${1} ${2}
	fi
}

mkdir -p ~/.config/nvim/

# symlink to dotfiles
deploy $INSTALL_DIR/git/gitconfig ~/.gitconfig
deploy $INSTALL_DIR/git/gitignore ~/.gitignore
deploy $INSTALL_DIR/tmux/tmux.conf ~/.tmux.conf
deploy $INSTALL_DIR/zsh/zshrc ~/.zshrc
deploy $INSTALL_DIR/nvim/init.vim ~/.config/nvim/init.vim

# Install the vim-plug plugin 
echo "Downloading vim-plug"
curl -fsLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# clone some repositories
clone https://github.com/junegunn/fzf.git             ~/.fzf
clone https://github.com/syndbg/goenv.git             ~/.goenv
clone https://github.com/pyenv/pyenv.git              ~/.pyenv
clone https://github.com/pyenv/pyenv-doctor.git       ~/.pyenv/plugins/pyenv-doctor
clone https://github.com/pyenv/pyenv-installer.git    ~/.pyenv/plugins/pyenv-installer
clone https://github.com/pyenv/pyenv-update.git       ~/.pyenv/plugins/pyenv-update
clone https://github.com/pyenv/pyenv-virtualenv.git   ~/.pyenv/plugins/pyenv-virtualenv
clone https://github.com/pyenv/pyenv-which-ext.git    ~/.pyenv/plugins/pyenv-which-ext
clone https://github.com/nodenv/nodenv.git            ~/.nodenv
clone https://github.com/nodenv/node-build.git        ~/.nodenv/plugins/node-build
clone https://github.com/nodenv/nodenv-package-rehash ~/.nodenv/plugins/nodenv-package-rehash.git

# post clone 
~/.fzf/install --bin
