#!/bin/sh

INSTALL_DIR=~/.dotfiles

if [ ! -d $INSTALL_DIR ]; then
	echo "Ops! dotfies must be installed on $INSTALL_DIR"
	exit 1
fi

deploy() {
	[ -f $2 ] && rm -f $2
	ln -s $1 $2
}

deploy $INSTALL_DIR/vim/vimrc ~/.vimrc
deploy $INSTALL_DIR/git/gitconfig ~/.gitconfig
deploy $INSTALL_DIR/git/gitignore ~/.gitignore
deploy $INSTALL_DIR/tmux/tmux.conf ~/.tmux.conf
deploy $INSTALL_DIR/zsh/ ~/.zsh
deploy $INSTALL_DIR/zsh/zshrc ~/.zshrc

# install oh-my-zsh
[ ! -d ~/.oh-my-zsh ] && git clone http://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh


